CREATE DATABASE sicos;

CREATE TABLE `provincia` (
	`ID` BIGINT(20) NOT NULL AUTO_INCREMENT,
	`NOMBRE` VARCHAR(50) NOT NULL,
	PRIMARY KEY (`ID`)
);

INSERT INTO provincia (NOMBRE) VALUE ('BUENOS AIRES');
INSERT INTO provincia (NOMBRE) VALUE ('SALTA');
INSERT INTO provincia (NOMBRE) VALUE ('JUJUY');
INSERT INTO provincia (NOMBRE) VALUE ('CHACO');
INSERT INTO provincia (NOMBRE) VALUE ('FORMOSA');
INSERT INTO provincia (NOMBRE) VALUE ('CORRIENTES');
INSERT INTO provincia (NOMBRE) VALUE ('MISIONES');
INSERT INTO provincia (NOMBRE) VALUE ('SAN JUAN');
INSERT INTO provincia (NOMBRE) VALUE ('SAN LUIS');
INSERT INTO provincia (NOMBRE) VALUE ('SANTA FE');
INSERT INTO provincia (NOMBRE) VALUE ('CORDOBA');
INSERT INTO provincia (NOMBRE) VALUE ('ENTRE RIOS');
INSERT INTO provincia (NOMBRE) VALUE ('RIO NEGRO');
INSERT INTO provincia (NOMBRE) VALUE ('NEUQUEN');
INSERT INTO provincia (NOMBRE) VALUE ('SANTA CRUZ');
INSERT INTO provincia (NOMBRE) VALUE ('TIERRA DEL FUEGO');
INSERT INTO provincia (NOMBRE) VALUE ('LA PAMPA');
INSERT INTO provincia (NOMBRE) VALUE ('MENDOZA');
INSERT INTO provincia (NOMBRE) VALUE ('TUCUMAN');
INSERT INTO provincia (NOMBRE) VALUE ('CHUBUT');
INSERT INTO provincia (NOMBRE) VALUE ('LA RIOJA');
INSERT INTO provincia (NOMBRE) VALUE ('CATAMARCA');
INSERT INTO provincia (NOMBRE) VALUE ('SANTIAGO DEL ESTERO');

CREATE TABLE `ciudad` (
	`ID` BIGINT(20) NOT NULL AUTO_INCREMENT,
	`NOMBRE` VARCHAR(50) NOT NULL,
	`PROVINCIA_ID` BIGINT(20) NOT NULL,
	PRIMARY KEY (`ID`),
	INDEX `FK_ciudad_provincia` (`PROVINCIA_ID`),
	CONSTRAINT `FK_ciudad_provincia` FOREIGN KEY (`PROVINCIA_ID`) REFERENCES `sicos`.`provincia` (`ID`) ON UPDATE NO ACTION ON DELETE NO ACTION
);

INSERT INTO ciudad (NOMBRE, PROVINCIA_ID) VALUES ('OLAVARRIA', (SELECT ID FROM provincia WHERE NOMBRE = 'BUENOS AIRES'));
INSERT INTO ciudad (NOMBRE, PROVINCIA_ID) VALUES ('BOLIVAR', (SELECT ID FROM provincia WHERE NOMBRE = 'BUENOS AIRES'));
INSERT INTO ciudad (NOMBRE, PROVINCIA_ID) VALUES ('LA PLATA', (SELECT ID FROM provincia WHERE NOMBRE = 'BUENOS AIRES'));
INSERT INTO ciudad (NOMBRE, PROVINCIA_ID) VALUES ('METAN', (SELECT ID FROM provincia WHERE NOMBRE = 'SALTA'));
INSERT INTO ciudad (NOMBRE, PROVINCIA_ID) VALUES ('ORAN', (SELECT ID FROM provincia WHERE NOMBRE = 'SALTA'));
INSERT INTO ciudad (NOMBRE, PROVINCIA_ID) VALUES ('LOS ANDES', (SELECT ID FROM provincia WHERE NOMBRE = 'SALTA'));
INSERT INTO ciudad (NOMBRE, PROVINCIA_ID) VALUES ('CAFAYATE', (SELECT ID FROM provincia WHERE NOMBRE = 'SALTA'));
INSERT INTO ciudad (NOMBRE, PROVINCIA_ID) VALUES ('HUMAHUACA', (SELECT ID FROM provincia WHERE NOMBRE = 'JUJUY'));
INSERT INTO ciudad (NOMBRE, PROVINCIA_ID) VALUES ('TILCARA', (SELECT ID FROM provincia WHERE NOMBRE = 'JUJUY'));
INSERT INTO ciudad (NOMBRE, PROVINCIA_ID) VALUES ('PALPALA', (SELECT ID FROM provincia WHERE NOMBRE = 'JUJUY'));
INSERT INTO ciudad (NOMBRE, PROVINCIA_ID) VALUES ('RESISTENCIA', (SELECT ID FROM provincia WHERE NOMBRE = 'CHACO'));
INSERT INTO ciudad (NOMBRE, PROVINCIA_ID) VALUES ('VILLA ANGELA', (SELECT ID FROM provincia WHERE NOMBRE = 'CHACO'));
INSERT INTO ciudad (NOMBRE, PROVINCIA_ID) VALUES ('BARRANQUERAS', (SELECT ID FROM provincia WHERE NOMBRE = 'CHACO'));
INSERT INTO ciudad (NOMBRE, PROVINCIA_ID) VALUES ('CLORINDA', (SELECT ID FROM provincia WHERE NOMBRE = 'FORMOSA'));
INSERT INTO ciudad (NOMBRE, PROVINCIA_ID) VALUES ('HERRADURA', (SELECT ID FROM provincia WHERE NOMBRE = 'FORMOSA'));
INSERT INTO ciudad (NOMBRE, PROVINCIA_ID) VALUES ('LAS LOMITAS', (SELECT ID FROM provincia WHERE NOMBRE = 'FORMOSA'));
INSERT INTO ciudad (NOMBRE, PROVINCIA_ID) VALUES ('MERCEDES', (SELECT ID FROM provincia WHERE NOMBRE = 'CORRIENTES'));
INSERT INTO ciudad (NOMBRE, PROVINCIA_ID) VALUES ('ITATI', (SELECT ID FROM provincia WHERE NOMBRE = 'CORRIENTES'));
INSERT INTO ciudad (NOMBRE, PROVINCIA_ID) VALUES ('GOYA', (SELECT ID FROM provincia WHERE NOMBRE = 'CORRIENTES'));
INSERT INTO ciudad (NOMBRE, PROVINCIA_ID) VALUES ('POSADAS', (SELECT ID FROM provincia WHERE NOMBRE = 'MISIONES'));
INSERT INTO ciudad (NOMBRE, PROVINCIA_ID) VALUES ('PUERTO IGUAZU', (SELECT ID FROM provincia WHERE NOMBRE = 'MISIONES'));
INSERT INTO ciudad (NOMBRE, PROVINCIA_ID) VALUES ('MONTECARLO', (SELECT ID FROM provincia WHERE NOMBRE = 'MISIONES'));
INSERT INTO ciudad (NOMBRE, PROVINCIA_ID) VALUES ('CHIMBAS', (SELECT ID FROM provincia WHERE NOMBRE = 'SAN JUAN'));
INSERT INTO ciudad (NOMBRE, PROVINCIA_ID) VALUES ('RIVADAVIA', (SELECT ID FROM provincia WHERE NOMBRE = 'SAN JUAN'));
INSERT INTO ciudad (NOMBRE, PROVINCIA_ID) VALUES ('POCITO', (SELECT ID FROM provincia WHERE NOMBRE = 'SAN JUAN'));
INSERT INTO ciudad (NOMBRE, PROVINCIA_ID) VALUES ('SAN LUIS', (SELECT ID FROM provincia WHERE NOMBRE = 'SAN LUIS'));
INSERT INTO ciudad (NOMBRE, PROVINCIA_ID) VALUES ('VILLA MERCEDES', (SELECT ID FROM provincia WHERE NOMBRE = 'SAN LUIS'));
INSERT INTO ciudad (NOMBRE, PROVINCIA_ID) VALUES ('MERLO', (SELECT ID FROM provincia WHERE NOMBRE = 'SAN LUIS'));
INSERT INTO ciudad (NOMBRE, PROVINCIA_ID) VALUES ('VENADO TUERTO', (SELECT ID FROM provincia WHERE NOMBRE = 'SANTA FE'));
INSERT INTO ciudad (NOMBRE, PROVINCIA_ID) VALUES ('RUFINO', (SELECT ID FROM provincia WHERE NOMBRE = 'SANTA FE'));
INSERT INTO ciudad (NOMBRE, PROVINCIA_ID) VALUES ('SUNCHALES', (SELECT ID FROM provincia WHERE NOMBRE = 'SANTA FE'));
INSERT INTO ciudad (NOMBRE, PROVINCIA_ID) VALUES ('ALTA GRACIA', (SELECT ID FROM provincia WHERE NOMBRE = 'CORDOBA'));
INSERT INTO ciudad (NOMBRE, PROVINCIA_ID) VALUES ('VILLA CARLOS PAZ', (SELECT ID FROM provincia WHERE NOMBRE = 'CORDOBA'));
INSERT INTO ciudad (NOMBRE, PROVINCIA_ID) VALUES ('JESUS MARIA', (SELECT ID FROM provincia WHERE NOMBRE = 'CORDOBA'));
INSERT INTO ciudad (NOMBRE, PROVINCIA_ID) VALUES ('COSQUIN', (SELECT ID FROM provincia WHERE NOMBRE = 'CORDOBA'));
INSERT INTO ciudad (NOMBRE, PROVINCIA_ID) VALUES ('RIO CUARTO', (SELECT ID FROM provincia WHERE NOMBRE = 'CORDOBA'));
INSERT INTO ciudad (NOMBRE, PROVINCIA_ID) VALUES ('PARANA', (SELECT ID FROM provincia WHERE NOMBRE = 'ENTRE RIOS'));
INSERT INTO ciudad (NOMBRE, PROVINCIA_ID) VALUES ('CONCORDIA', (SELECT ID FROM provincia WHERE NOMBRE = 'ENTRE RIOS'));
INSERT INTO ciudad (NOMBRE, PROVINCIA_ID) VALUES ('GUALEGUAYCHU', (SELECT ID FROM provincia WHERE NOMBRE = 'ENTRE RIOS'));
INSERT INTO ciudad (NOMBRE, PROVINCIA_ID) VALUES ('BARILOCHE', (SELECT ID FROM provincia WHERE NOMBRE = 'RIO NEGRO'));
INSERT INTO ciudad (NOMBRE, PROVINCIA_ID) VALUES ('VIEDMA', (SELECT ID FROM provincia WHERE NOMBRE = 'RIO NEGRO'));
INSERT INTO ciudad (NOMBRE, PROVINCIA_ID) VALUES ('CIPOLLETTI', (SELECT ID FROM provincia WHERE NOMBRE = 'RIO NEGRO'));
INSERT INTO ciudad (NOMBRE, PROVINCIA_ID) VALUES ('JUNIN DE LOS ANDES', (SELECT ID FROM provincia WHERE NOMBRE = 'NEUQUEN'));
INSERT INTO ciudad (NOMBRE, PROVINCIA_ID) VALUES ('SAN MARTIN DE LOS ANDES', (SELECT ID FROM provincia WHERE NOMBRE = 'NEUQUEN'));
INSERT INTO ciudad (NOMBRE, PROVINCIA_ID) VALUES ('PIEDRA DEL AGUILA', (SELECT ID FROM provincia WHERE NOMBRE = 'NEUQUEN'));
INSERT INTO ciudad (NOMBRE, PROVINCIA_ID) VALUES ('CALAFATE', (SELECT ID FROM provincia WHERE NOMBRE = 'SANTA CRUZ'));
INSERT INTO ciudad (NOMBRE, PROVINCIA_ID) VALUES ('RIO GALLEGOS', (SELECT ID FROM provincia WHERE NOMBRE = 'SANTA CRUZ'));
INSERT INTO ciudad (NOMBRE, PROVINCIA_ID) VALUES ('PUERTO DESEADO', (SELECT ID FROM provincia WHERE NOMBRE = 'SANTA CRUZ'));
INSERT INTO ciudad (NOMBRE, PROVINCIA_ID) VALUES ('USUAHIA', (SELECT ID FROM provincia WHERE NOMBRE = 'TIERRA DEL FUEGO'));
INSERT INTO ciudad (NOMBRE, PROVINCIA_ID) VALUES ('SAN SEBASTIAN', (SELECT ID FROM provincia WHERE NOMBRE = 'TIERRA DEL FUEGO'));
INSERT INTO ciudad (NOMBRE, PROVINCIA_ID) VALUES ('LAGO ESCONDIDO', (SELECT ID FROM provincia WHERE NOMBRE = 'TIERRA DEL FUEGO'));
INSERT INTO ciudad (NOMBRE, PROVINCIA_ID) VALUES ('SANTA ROSA', (SELECT ID FROM provincia WHERE NOMBRE = 'LA PAMPA'));
INSERT INTO ciudad (NOMBRE, PROVINCIA_ID) VALUES ('GENERAL PICO', (SELECT ID FROM provincia WHERE NOMBRE = 'LA PAMPA'));
INSERT INTO ciudad (NOMBRE, PROVINCIA_ID) VALUES ('GENERAL ACHA', (SELECT ID FROM provincia WHERE NOMBRE = 'LA PAMPA'));
INSERT INTO ciudad (NOMBRE, PROVINCIA_ID) VALUES ('GUAMALLEN', (SELECT ID FROM provincia WHERE NOMBRE = 'MENDOZA'));
INSERT INTO ciudad (NOMBRE, PROVINCIA_ID) VALUES ('LAS HERAS', (SELECT ID FROM provincia WHERE NOMBRE = 'MENDOZA'));
INSERT INTO ciudad (NOMBRE, PROVINCIA_ID) VALUES ('GODOY CRUZ', (SELECT ID FROM provincia WHERE NOMBRE = 'MENDOZA'));
INSERT INTO ciudad (NOMBRE, PROVINCIA_ID) VALUES ('SAN RAFAEL', (SELECT ID FROM provincia WHERE NOMBRE = 'MENDOZA'));
INSERT INTO ciudad (NOMBRE, PROVINCIA_ID) VALUES ('CONCEPCION', (SELECT ID FROM provincia WHERE NOMBRE = 'TUCUMAN'));
INSERT INTO ciudad (NOMBRE, PROVINCIA_ID) VALUES ('BELLA VISTA', (SELECT ID FROM provincia WHERE NOMBRE = 'TUCUMAN'));
INSERT INTO ciudad (NOMBRE, PROVINCIA_ID) VALUES ('TAFI DEL VALLE', (SELECT ID FROM provincia WHERE NOMBRE = 'TUCUMAN'));
INSERT INTO ciudad (NOMBRE, PROVINCIA_ID) VALUES ('PUERTO MADRYN', (SELECT ID FROM provincia WHERE NOMBRE = 'CHUBUT'));
INSERT INTO ciudad (NOMBRE, PROVINCIA_ID) VALUES ('RAWSON', (SELECT ID FROM provincia WHERE NOMBRE = 'CHUBUT'));
INSERT INTO ciudad (NOMBRE, PROVINCIA_ID) VALUES ('COMODORO RIVADAVIA', (SELECT ID FROM provincia WHERE NOMBRE = 'CHUBUT'));
INSERT INTO ciudad (NOMBRE, PROVINCIA_ID) VALUES ('CHILECITO', (SELECT ID FROM provincia WHERE NOMBRE = 'LA RIOJA'));
INSERT INTO ciudad (NOMBRE, PROVINCIA_ID) VALUES ('VILLA SANAGASTA', (SELECT ID FROM provincia WHERE NOMBRE = 'LA RIOJA'));
INSERT INTO ciudad (NOMBRE, PROVINCIA_ID) VALUES ('CHEPES', (SELECT ID FROM provincia WHERE NOMBRE = 'LA RIOJA'));
INSERT INTO ciudad (NOMBRE, PROVINCIA_ID) VALUES ('VALLE VIEJO', (SELECT ID FROM provincia WHERE NOMBRE = 'CATAMARCA'));
INSERT INTO ciudad (NOMBRE, PROVINCIA_ID) VALUES ('SANTA MARIA', (SELECT ID FROM provincia WHERE NOMBRE = 'CATAMARCA'));
INSERT INTO ciudad (NOMBRE, PROVINCIA_ID) VALUES ('LOS ALTOS', (SELECT ID FROM provincia WHERE NOMBRE = 'CATAMARCA'));
INSERT INTO ciudad (NOMBRE, PROVINCIA_ID) VALUES ('COLONIA DORA', (SELECT ID FROM provincia WHERE NOMBRE = 'SANTIAGO DEL ESTERO'));
INSERT INTO ciudad (NOMBRE, PROVINCIA_ID) VALUES ('CLODOMIRA', (SELECT ID FROM provincia WHERE NOMBRE = 'SANTIAGO DEL ESTERO'));
INSERT INTO ciudad (NOMBRE, PROVINCIA_ID) VALUES ('BANDERA', (SELECT ID FROM provincia WHERE NOMBRE = 'SANTIAGO DEL ESTERO'));

CREATE TABLE `persona` (
	`ID` BIGINT(20) NOT NULL AUTO_INCREMENT,
	`NOMBRE` VARCHAR(50) NOT NULL,
	`APELLIDO` VARCHAR(50) NOT NULL,
	`DNI` INT(11) NOT NULL,
	`FECHA_NAC` DATE NOT NULL,
	`CIUDAD_ID` BIGINT(20) NOT NULL,
	PRIMARY KEY (`ID`),
	INDEX `FK_persona_ciudad` (`CIUDAD_ID`),
	CONSTRAINT `FK_persona_ciudad` FOREIGN KEY (`CIUDAD_ID`) REFERENCES `sicos`.`ciudad` (`ID`) ON UPDATE NO ACTION ON DELETE NO ACTION
);

CREATE TABLE `parentesco` (
	`ID` BIGINT(20) NOT NULL AUTO_INCREMENT,
	`DESCRIPCION` VARCHAR(50) NOT NULL,
	PRIMARY KEY (`ID`)
);

CREATE TABLE `relacion_parentesco` (
	`ID` BIGINT(20) NOT NULL AUTO_INCREMENT,
	`DESDE_RELACION` BIGINT(20) NOT NULL,
	`HASTA_RELACION` BIGINT(20) NOT NULL,
	`PARENTESCO_ID` BIGINT(20) NOT NULL,
	PRIMARY KEY (`ID`),
	INDEX `FK__persona` (`DESDE_RELACION`),
	INDEX `FK__persona_2` (`HASTA_RELACION`),
	INDEX `FK_relacion_parentesco_parentesco` (`PARENTESCO_ID`),
	CONSTRAINT `FK__persona` FOREIGN KEY (`DESDE_RELACION`) REFERENCES `sicos`.`persona` (`ID`) ON UPDATE NO ACTION ON DELETE NO ACTION,
	CONSTRAINT `FK__persona_2` FOREIGN KEY (`HASTA_RELACION`) REFERENCES `sicos`.`persona` (`ID`) ON UPDATE NO ACTION ON DELETE NO ACTION,
	CONSTRAINT `FK_relacion_parentesco_parentesco` FOREIGN KEY (`PARENTESCO_ID`) REFERENCES `sicos`.`parentesco` (`ID`) ON UPDATE NO ACTION ON DELETE NO ACTION
);

CREATE PROCEDURE sicos.INSERTAR_PERSONA(IN `NOM` VARCHAR(50),
	IN `APE` VARCHAR(50),
	IN `DNI` INT,
	IN `NAC` DATE,
	IN `NOMBRE_CIUDAD` VARCHAR(50))
	INSERT INTO PERSONA(NOMBRE, APELLIDO, DNI, FECHA_NAC, CIUDAD_ID) 
		VALUES (NOM, APE, DNI, NAC, (SELECT ID FROM CIUDAD WHERE NOMBRE = NOMBRE_CIUDAD));

CREATE FUNCTION sicos.cuadrado(
	`s` INT
)
RETURNS int(11)
RETURN s*s;
